name: Check BE PR

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install yarn modules
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run audit
        run: yarn audit:all
